# Generated by Django 2.2.9 on 2020-01-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
