# Generated by Django 2.2.9 on 2020-01-31 12:30

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='noHp',
            field=models.CharField(max_length=20, validators=[utils.validators.validate_noHp, utils.validators.validate_noHp_exist]),
        ),
    ]
