# Generated by Django 2.2.9 on 2020-02-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_auto_20200131_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogModel',
        ),
    ]
