# Generated by Django 2.2.9 on 2020-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='confirm_message',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.CharField(default='Zukron Alviandy Rahmadhan', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_confirm_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='value_confirm_message',
            field=models.BooleanField(default=False),
        ),
    ]
