# Generated by Django 2.2.9 on 2020-02-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200201_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='confirm_message',
            field=models.TextField(blank=True),
        ),
    ]
