# Generated by Django 2.2.9 on 2020-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200201_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
